using System;
using System.Collections.Generic;
using MegaCrit.Sts2.Core.Localization;

namespace Sts2SkinManager.Localization;

public static class Strings
{
    public static string Get(string key)
    {
        var lang = GetCurrentLanguage();
        if (_tables.TryGetValue(lang, out var table) && table.TryGetValue(key, out var value)) return value;
        if (_tables.TryGetValue("ENG", out var eng) && eng.TryGetValue(key, out var engValue)) return engValue;
        return key;
    }

    public static string Get(string key, params object[] args)
    {
        var raw = Get(key);
        try { return args.Length == 0 ? raw : string.Format(raw, args); }
        catch { return raw; }
    }

    private static string GetCurrentLanguage()
    {
        try { return (LocManager.Instance?.Language ?? "ENG").ToUpperInvariant(); }
        catch { return "ENG"; }
    }

    private static readonly Dictionary<string, Dictionary<string, string>> _tables = new(StringComparer.OrdinalIgnoreCase)
    {
        ["ENG"] = new()
        {
            ["skin_label"] = "Skin",
            ["no_variants"] = "No detected skins",
            ["not_configured"] = "No configuration",
            ["modal_title"] = "Sts2 Skin Manager",
            ["modal_body"] = "To change the skin, STS2 must restart.\nChoose: restart now, or cancel the change.\n\nAuto-restart in {0}s via Steam.",
            ["load_order_modal_title"] = "Sts2 Skin Manager — First setup",
            ["load_order_modal_body"] = "Skin Manager must load before other mods to block their forced changes (e.g. character size override).\n\nMod load order was auto-corrected.\nRestart STS2 once to apply.\n\nAuto-restart in {0}s via Steam.",
            ["dll_skin_modal_title"] = "Sts2 Skin Manager — DLL skin detected",
            ["dll_skin_modal_body_summary"] = "One or more DLL-based character skins were detected (mod uses Harmony to swap a character).\nAuto-assigned to a base character — see logs for details.\n\nRestart to manage them like normal skins (toggle from the dropdown).\n\nAuto-restart in {0}s via Steam.",
            ["btn_restart_now"] = "Restart now",
            ["btn_restart_later"] = "Restart later",
            ["card_packs_header"] = "Card skins",
            ["save_changes"] = "Save",
            ["discard_changes"] = "Discard",
            ["preview_unavailable"] = "no preview",
            ["preview_toggle_tooltip"] = "Toggle skin preview",
            ["alias_edit_tooltip"] = "Rename display label",
            ["alias_placeholder"] = "Display name (blank = use mod ID)",
            ["alias_save_tooltip"] = "Save name",
            ["alias_cancel_tooltip"] = "Cancel",
            ["alias_dup_modid"] = "Name conflicts with an existing mod ID",
            ["alias_dup_alias"] = "Another mod already uses this name",
            ["alias_same_as_own"] = "Same as the mod ID — leave blank to use it",
            ["mixed_panel_header"] = "Mixed mods (spine + extras)",
            ["mixed_panel_tooltip"] = "Toggle mixed mods (spine + extras).",
            ["mixed_vanilla_body_tooltip"] = "On: appearance follows your character-select pick; this mod's cards stay. (Mixed mod must be on.)",
            ["vanilla_body_on"] = "Selected look",
            ["vanilla_body_off"] = "Mod look",
            ["mixed_indicator_tooltip"] = "📦 Mixed mod — applies spine + card art / events together.",
            ["mixed_panel_help"] = "Character pick from the dropdown loads first.",
            ["skin_manager_section_header"] = "Skin manager",
            ["all_mods_panel_header"] = "Other mods",
            ["all_mods_panel_help"] = "Character skin variants, content mods, and DLL mods that don't fit Card or Mixed tabs. Toggle the checkbox to enable/disable management. Pick a base character to force the mod into that skin slot (its DLL will be blocked when another skin is active).",
            ["all_mods_action_auto"] = "Auto",
            ["all_mods_action_skip"] = "Don't manage",
            ["all_mods_action_skin_for"] = "Skin for {0}",
            ["all_mods_action_pending"] = "(decide later)",
            ["all_mods_badge_character"] = "Character",
            ["all_mods_badge_character_x"] = "Char: {0}",
            ["all_mods_badge_card"] = "Card",
            ["all_mods_badge_mixed"] = "Mixed",
            ["all_mods_badge_mixed_x"] = "Mixed: {0}",
            ["all_mods_badge_skip"] = "Skipped",
            ["all_mods_badge_pending"] = "Pending",
            ["all_mods_tooltip_content"] = "Defines new monsters / events / cards — skinning it would disable that content.",
            ["all_mods_toggle_tooltip"] = "Whether this mod is currently loaded by the game. Toggle off to deactivate a character variant.",
            ["card_panel_empty"] = "No card skin mods detected.",
            ["mixed_panel_empty"] = "No mixed mods (spine + extras) detected.",
            ["applied_tab_title"] = "Applied",
            ["tab_cards"] = "Cards",
            ["tab_mixed"] = "Mixed",
            ["tab_other"] = "Other",
            ["tab_custom_characters"] = "Custom Characters",
            ["custom_char_panel_help"] = "Extra characters added by mods (BaseLib-style). These aren't skins — toggle a checkbox to enable or disable a custom character. Changes apply to the game's mod list and take effect after restarting STS2.",
            ["custom_char_toggle_tooltip"] = "Whether this custom character is loaded by the game. Toggle off to disable it; restart STS2 to apply.",
            ["applied_copy"] = "📋 Copy",
            ["applied_copied"] = "✓ Copied",
            ["applied_copy_tooltip"] = "Copy this summary (handy for bug reports).",
            ["applied_pending_note"] = "Pending changes — restart to apply.",
            ["applied_characters"] = "Characters",
            ["applied_custom_characters"] = "Custom characters",
            ["applied_vanilla"] = "Vanilla (default)",
            ["applied_none"] = "None",
            ["applied_after_restart"] = "after restart",
            ["applied_dll_tag"] = "DLL",
            ["applied_not_mounted"] = "not mounted — check load order / logs",
            ["applied_other_disabled"] = "Disabled mods",
            ["applied_all_vanilla"] = "All characters use the default look.",
        },
        ["KOR"] = new()
        {
            ["skin_label"] = "스킨",
            ["no_variants"] = "감지된 스킨 목록 없음",
            ["not_configured"] = "설정 없음",
            ["modal_title"] = "Sts2 스킨 매니저",
            ["modal_body"] = "스킨을 변경하려면 게임을 재시작해야 해요.\n즉시 재시작할지 변경을 취소할지 선택해주세요.\n\n{0}초 뒤 자동으로 재시작됩니다.",
            ["load_order_modal_title"] = "Sts2 스킨 매니저 — 첫 설치",
            ["load_order_modal_body"] = "스킨 매니저가 다른 mod 보다 먼저 로드되어야\n다른 캐릭터 mod 의 강제 변경(예: 크기 강제 조정)을 막을 수 있어요.\n\nmod 로드 순서를 자동으로 정렬했어요.\n적용하려면 STS2 를 한 번 재시작해 주세요.\n\n{0}초 뒤 자동으로 재시작됩니다.",
            ["dll_skin_modal_title"] = "Sts2 스킨 매니저 — DLL 기반 스킨 감지",
            ["dll_skin_modal_body_summary"] = "DLL 로 캐릭터를 교체하는 mod 가 감지됐어요 (Harmony 로 캐릭터 swap).\n자동으로 어느 캐릭터 스킨인지 추정해서 등록했어요 — 로그에서 매핑 결과 확인 가능.\n\n다른 일반 스킨처럼 드롭다운으로 토글하려면 재시작해 주세요.\n\n{0}초 뒤 자동으로 재시작됩니다.",
            ["btn_restart_now"] = "지금 재시작",
            ["btn_restart_later"] = "나중에 재시작",
            ["card_packs_header"] = "카드 스킨",
            ["save_changes"] = "저장",
            ["discard_changes"] = "되돌리기",
            ["preview_unavailable"] = "미리보기 없음",
            ["preview_toggle_tooltip"] = "스킨 미리보기 토글",
            ["alias_edit_tooltip"] = "표시 이름 변경",
            ["alias_placeholder"] = "표시 이름 (비우면 mod ID 사용)",
            ["alias_save_tooltip"] = "이름 저장",
            ["alias_cancel_tooltip"] = "취소",
            ["alias_dup_modid"] = "다른 mod ID 와 겹쳐요",
            ["alias_dup_alias"] = "다른 mod 가 이미 쓰는 이름이에요",
            ["alias_same_as_own"] = "mod ID 와 같아요 — 비우면 그대로 사용",
            ["mixed_panel_header"] = "혼합 mod (스파인 + 추가요소)",
            ["mixed_panel_tooltip"] = "혼합 mod 켜고 끄기 (스파인 + 추가요소)",
            ["mixed_vanilla_body_tooltip"] = "켜면 외형은 위 캐릭터 선택을 따르고, 이 모드의 카드는 유지됩니다. (혼합 mod가 켜져 있어야 함)",
            ["vanilla_body_on"] = "캐릭터 선택 외형",
            ["vanilla_body_off"] = "모드 외형",
            ["mixed_indicator_tooltip"] = "📦 혼합 mod — 스파인과 카드 아트 / 이벤트를 함께 적용",
            ["mixed_panel_help"] = "캐릭터 선택 모드가 먼저 로드됩니다.",
            ["skin_manager_section_header"] = "스킨 매니저",
            ["all_mods_panel_header"] = "그 외 mod",
            ["all_mods_panel_help"] = "카드/혼합 탭에 들어가지 않는 캐릭터 스킨, 컨텐츠 mod, DLL mod 목록. 체크박스로 관리 켜기/끄기. 베이스 캐릭터를 골라 그 슬롯에 강제 지정 가능 — 다른 스킨이 활성화되면 이 mod 의 DLL 이 차단됩니다.",
            ["all_mods_action_auto"] = "자동",
            ["all_mods_action_skip"] = "관리 안 함",
            ["all_mods_action_skin_for"] = "{0} 스킨으로",
            ["all_mods_action_pending"] = "(나중에 결정)",
            ["all_mods_badge_character"] = "캐릭터",
            ["all_mods_badge_character_x"] = "캐릭터: {0}",
            ["all_mods_badge_card"] = "카드",
            ["all_mods_badge_mixed"] = "혼합",
            ["all_mods_badge_mixed_x"] = "혼합: {0}",
            ["all_mods_badge_skip"] = "관리 안 함",
            ["all_mods_badge_pending"] = "미정",
            ["all_mods_tooltip_content"] = "새 몬스터 / 이벤트 / 카드를 정의함 — 스킨 처리하면 해당 컨텐츠가 비활성화됩니다.",
            ["all_mods_toggle_tooltip"] = "이 mod 가 게임에 로드되어 있는지 표시. 캐릭터 변형을 끄려면 체크 해제.",
            ["card_panel_empty"] = "감지된 카드 스킨 mod 없음.",
            ["mixed_panel_empty"] = "감지된 혼합 mod (스파인 + 추가요소) 없음.",
            ["applied_tab_title"] = "적용됨",
            ["tab_cards"] = "카드",
            ["tab_mixed"] = "혼합",
            ["tab_other"] = "기타",
            ["tab_custom_characters"] = "커스텀 캐릭터",
            ["custom_char_panel_help"] = "mod 가 추가한 커스텀 캐릭터(BaseLib 계열) 목록입니다. 스킨이 아니라 캐릭터 자체예요 — 체크박스로 켜고 끌 수 있습니다. 변경은 게임 mod 목록에 적용되며 STS2 를 재시작해야 반영됩니다.",
            ["custom_char_toggle_tooltip"] = "이 커스텀 캐릭터가 게임에 로드되는지 여부. 끄면 비활성화되고, STS2 재시작 시 적용됩니다.",
            ["applied_copy"] = "📋 복사",
            ["applied_copied"] = "✓ 복사됨",
            ["applied_copy_tooltip"] = "이 요약을 복사 (버그 신고할 때 편해요).",
            ["applied_pending_note"] = "변경 대기 중 — 재시작하면 적용돼요.",
            ["applied_characters"] = "캐릭터",
            ["applied_custom_characters"] = "커스텀 캐릭터",
            ["applied_vanilla"] = "기본 (바닐라)",
            ["applied_none"] = "없음",
            ["applied_after_restart"] = "재시작 후",
            ["applied_dll_tag"] = "DLL",
            ["applied_not_mounted"] = "마운트 안 됨 — 로드 순서 / 로그 확인",
            ["applied_other_disabled"] = "비활성화된 모드",
            ["applied_all_vanilla"] = "모든 캐릭터가 기본 외형을 사용 중이에요.",
        },
        ["JPN"] = new()
        {
            ["applied_copy"] = "📋 コピー",
            ["applied_copied"] = "✓ コピーしました",
            ["applied_copy_tooltip"] = "この概要をコピー（不具合報告に便利）。",
            ["skin_label"] = "スキン",
            ["no_variants"] = "検出されたスキンなし",
            ["not_configured"] = "設定なし",
            ["modal_title"] = "Sts2 スキンマネージャー",
            ["modal_body"] = "スキンを変更するにはSTS2の再起動が必要です。\nすぐに再起動するか、変更を取り消すか選んでください。\n\n{0}秒後にSteamで自動再起動します。",
            ["load_order_modal_title"] = "Sts2 スキンマネージャー — 初回セットアップ",
            ["load_order_modal_body"] = "他キャラクター mod の強制変更(例:サイズ強制)を防ぐため、\nスキンマネージャーは他の mod より先に読み込まれる必要があります。\n\nmod 読み込み順を自動で並べ替えました。\n適用するには STS2 を一度再起動してください。\n\n{0}秒後にSteamで自動再起動します。",
            ["dll_skin_modal_title"] = "Sts2 スキンマネージャー — DLLスキン検出",
            ["dll_skin_modal_body_summary"] = "DLLでキャラクターを差し替えるmod(Harmonyでswap)を検出しました。\nどのキャラクターのスキンかを自動推定して登録しました — マッピングはログ参照。\n\n通常スキンと同様にドロップダウンで切替するには再起動してください。\n\n{0}秒後にSteamで自動再起動します。",
            ["btn_restart_now"] = "今すぐ再起動",
            ["btn_restart_later"] = "後で再起動",
            ["card_packs_header"] = "カードスキン",
            ["save_changes"] = "保存",
            ["discard_changes"] = "破棄",
            ["preview_unavailable"] = "プレビューなし",
            ["preview_toggle_tooltip"] = "スキンプレビュー切替",
            ["mixed_panel_header"] = "混合 mod (スパイン + 追加要素)",
            ["mixed_panel_tooltip"] = "混合 mod のオン・オフ (スパイン + 追加要素)",
            ["mixed_vanilla_body_tooltip"] = "オン: 外見は上のキャラ選択に従い、このMODのカードは維持。(混合MODがオンの時のみ)",
            ["vanilla_body_on"] = "選択した外見",
            ["vanilla_body_off"] = "MODの外見",
            ["mixed_indicator_tooltip"] = "📦 混合 mod — スパインとカードアート / イベントを一緒に適用",
            ["mixed_panel_help"] = "上のキャラクター選択が先に読み込まれます。",
            ["skin_manager_section_header"] = "スキンマネージャー",
        },
        ["ZHS"] = new()
        {
            ["applied_copy"] = "📋 复制",
            ["applied_copied"] = "✓ 已复制",
            ["applied_copy_tooltip"] = "复制此摘要（方便提交错误报告）。",
            ["skin_label"] = "皮肤",
            ["no_variants"] = "未检测到皮肤",
            ["not_configured"] = "无配置",
            ["modal_title"] = "Sts2 皮肤管理器",
            ["modal_body"] = "要更换皮肤,需要重启 STS2。\n请选择立即重启或取消更改。\n\n将在 {0} 秒后通过 Steam 自动重启。",
            ["load_order_modal_title"] = "Sts2 皮肤管理器 — 首次设置",
            ["load_order_modal_body"] = "皮肤管理器需要先于其他 mod 加载,\n才能阻止其他角色 mod 的强制修改(例如角色尺寸覆写)。\n\nmod 加载顺序已自动调整。\n请重启 STS2 一次以应用。\n\n将在 {0} 秒后通过 Steam 自动重启。",
            ["dll_skin_modal_title"] = "Sts2 皮肤管理器 — 检测到 DLL 皮肤",
            ["dll_skin_modal_body_summary"] = "检测到一个或多个使用 DLL 替换角色的 mod (通过 Harmony swap)。\n已自动判断对应的基础角色并登记 — 详见日志。\n\n要像普通皮肤一样从下拉菜单切换,请重启游戏。\n\n将在 {0} 秒后通过 Steam 自动重启。",
            ["btn_restart_now"] = "立即重启",
            ["btn_restart_later"] = "稍后重启",
            ["card_packs_header"] = "卡牌外观",
            ["save_changes"] = "保存",
            ["discard_changes"] = "丢弃",
            ["preview_unavailable"] = "无预览",
            ["preview_toggle_tooltip"] = "切换皮肤预览",
            ["mixed_panel_header"] = "混合 mod (骨骼 + 附加)",
            ["mixed_panel_tooltip"] = "切换混合 mod (骨骼 + 附加)",
            ["mixed_vanilla_body_tooltip"] = "开启时: 外观跟随上方角色选择，保留此模组的卡牌。(需启用混合模组)",
            ["vanilla_body_on"] = "所选外观",
            ["vanilla_body_off"] = "模组外观",
            ["mixed_indicator_tooltip"] = "📦 混合 mod — 同时应用骨骼与卡牌图 / 事件",
            ["mixed_panel_help"] = "上方角色选择优先加载。",
            ["skin_manager_section_header"] = "皮肤管理器",
        },
        ["ZHT"] = new()
        {
            ["applied_copy"] = "📋 複製",
            ["applied_copied"] = "✓ 已複製",
            ["applied_copy_tooltip"] = "複製此摘要（方便回報問題）。",
            ["skin_label"] = "皮膚",
            ["no_variants"] = "未偵測到皮膚",
            ["not_configured"] = "無配置",
            ["modal_title"] = "Sts2 皮膚管理器",
            ["modal_body"] = "要更換皮膚,需要重啟 STS2。\n請選擇立即重啟或取消變更。\n\n將在 {0} 秒後透過 Steam 自動重啟。",
            ["load_order_modal_title"] = "Sts2 皮膚管理器 — 首次設定",
            ["load_order_modal_body"] = "皮膚管理器需要比其他 mod 更早載入,\n才能阻擋其他角色 mod 的強制修改(例如角色尺寸覆寫)。\n\nmod 載入順序已自動調整。\n請重新啟動 STS2 一次以套用。\n\n將在 {0} 秒後透過 Steam 自動重新啟動。",
            ["dll_skin_modal_title"] = "Sts2 皮膚管理器 — 偵測到 DLL 皮膚",
            ["dll_skin_modal_body_summary"] = "偵測到一個或多個使用 DLL 替換角色的 mod(透過 Harmony swap)。\n已自動判斷對應的基礎角色並登記 — 詳見日誌。\n\n要像一般皮膚一樣從下拉選單切換,請重新啟動遊戲。\n\n將在 {0} 秒後透過 Steam 自動重新啟動。",
            ["btn_restart_now"] = "立即重啟",
            ["btn_restart_later"] = "稍後重啟",
            ["card_packs_header"] = "卡牌外觀",
            ["save_changes"] = "儲存",
            ["discard_changes"] = "捨棄",
            ["preview_unavailable"] = "無預覽",
            ["preview_toggle_tooltip"] = "切換皮膚預覽",
            ["mixed_panel_header"] = "混合 mod (骨架 + 附加)",
            ["mixed_panel_tooltip"] = "切換混合 mod (骨架 + 附加)",
            ["mixed_vanilla_body_tooltip"] = "開啟時: 外觀跟隨上方角色選擇，保留此模組的卡牌。(需啟用混合模組)",
            ["vanilla_body_on"] = "所選外觀",
            ["vanilla_body_off"] = "模組外觀",
            ["mixed_indicator_tooltip"] = "📦 混合 mod — 同時套用骨架與卡牌圖 / 事件",
            ["mixed_panel_help"] = "上方角色選擇優先載入。",
            ["skin_manager_section_header"] = "皮膚管理器",
        },
        ["DEU"] = new()
        {
            ["applied_copy"] = "📋 Kopieren",
            ["applied_copied"] = "✓ Kopiert",
            ["applied_copy_tooltip"] = "Diese Übersicht kopieren (praktisch für Fehlerberichte).",
            ["skin_label"] = "Skin",
            ["no_variants"] = "Keine erkannten Skins",
            ["not_configured"] = "Keine Konfiguration",
            ["modal_title"] = "Sts2 Skin Manager",
            ["modal_body"] = "Um den Skin zu ändern, muss STS2 neu starten.\nWähle: jetzt neu starten oder Änderung abbrechen.\n\nAutomatischer Neustart in {0}s über Steam.",
            ["load_order_modal_title"] = "Sts2 Skin Manager — Erste Einrichtung",
            ["load_order_modal_body"] = "Skin Manager muss vor anderen Mods geladen werden,\num deren erzwungene Änderungen (z. B. Charaktergröße) zu blockieren.\n\nDie Mod-Ladereihenfolge wurde automatisch korrigiert.\nStarte STS2 einmal neu, um es anzuwenden.\n\nAutomatischer Neustart in {0}s über Steam.",
            ["dll_skin_modal_title"] = "Sts2 Skin Manager — DLL-Skin erkannt",
            ["dll_skin_modal_body_summary"] = "Es wurden DLL-basierte Charakter-Skins erkannt (Mod nutzt Harmony zum Tausch).\nAutomatisch einem Basis-Charakter zugewiesen — Details im Log.\n\nNeustart, um sie wie normale Skins per Dropdown umzuschalten.\n\nAutomatischer Neustart in {0}s über Steam.",
            ["btn_restart_now"] = "Jetzt neu starten",
            ["btn_restart_later"] = "Später neu starten",
            ["card_packs_header"] = "Karten-Skins",
            ["save_changes"] = "Speichern",
            ["discard_changes"] = "Verwerfen",
            ["preview_unavailable"] = "keine Vorschau",
            ["preview_toggle_tooltip"] = "Skin-Vorschau umschalten",
            ["mixed_panel_header"] = "Gemischte Mods (Spine + Extras)",
            ["mixed_panel_tooltip"] = "Gemischte Mods umschalten (Spine + Extras)",
            ["mixed_vanilla_body_tooltip"] = "An: Aussehen folgt deiner Charakterauswahl; Karten dieses Mods bleiben. (Mixed-Mod muss an sein.)",
            ["vanilla_body_on"] = "Gewähltes Aussehen",
            ["vanilla_body_off"] = "Mod-Aussehen",
            ["mixed_indicator_tooltip"] = "📦 Gemischter Mod — wendet Spine + Kartenkunst / Events zusammen an",
            ["mixed_panel_help"] = "Charakterauswahl oben wird zuerst geladen.",
            ["skin_manager_section_header"] = "Skin-Manager",
        },
        ["FRA"] = new()
        {
            ["applied_copy"] = "📋 Copier",
            ["applied_copied"] = "✓ Copié",
            ["applied_copy_tooltip"] = "Copier ce récapitulatif (utile pour les rapports de bug).",
            ["skin_label"] = "Skin",
            ["no_variants"] = "Aucun skin détecté",
            ["not_configured"] = "Aucune configuration",
            ["modal_title"] = "Sts2 Skin Manager",
            ["modal_body"] = "Pour changer de skin, STS2 doit redémarrer.\nChoisissez : redémarrer maintenant ou annuler le changement.\n\nRedémarrage automatique dans {0}s via Steam.",
            ["load_order_modal_title"] = "Sts2 Skin Manager — Configuration initiale",
            ["load_order_modal_body"] = "Skin Manager doit se charger avant les autres mods\npour bloquer leurs modifications forcées (ex. taille de personnage).\n\nL'ordre de chargement des mods a été corrigé automatiquement.\nRedémarrez STS2 une fois pour appliquer.\n\nRedémarrage automatique dans {0}s via Steam.",
            ["dll_skin_modal_title"] = "Sts2 Skin Manager — Skin DLL détecté",
            ["dll_skin_modal_body_summary"] = "Des skins de personnage basés sur DLL ont été détectés (mod utilisant Harmony pour le swap).\nAttribution automatique à un personnage de base — voir les logs.\n\nRedémarrez pour les gérer via le menu déroulant comme des skins normaux.\n\nRedémarrage automatique dans {0}s via Steam.",
            ["btn_restart_now"] = "Redémarrer maintenant",
            ["btn_restart_later"] = "Redémarrer plus tard",
            ["card_packs_header"] = "Skins de cartes",
            ["save_changes"] = "Enregistrer",
            ["discard_changes"] = "Annuler",
            ["preview_unavailable"] = "pas d'aperçu",
            ["preview_toggle_tooltip"] = "Basculer l'aperçu du skin",
            ["mixed_panel_header"] = "Mods mixtes (squelette + extras)",
            ["mixed_panel_tooltip"] = "Activer/désactiver les mods mixtes (squelette + extras)",
            ["mixed_vanilla_body_tooltip"] = "Activé : l'apparence suit votre choix de personnage ; les cartes de ce mod sont conservées. (Le mod mixte doit être activé.)",
            ["vanilla_body_on"] = "Apparence choisie",
            ["vanilla_body_off"] = "Apparence du mod",
            ["mixed_indicator_tooltip"] = "📦 Mod mixte — applique squelette + cartes / événements ensemble",
            ["mixed_panel_help"] = "La sélection de personnage en haut est chargée en premier.",
            ["skin_manager_section_header"] = "Gestionnaire de skins",
        },
        ["SPA"] = new()
        {
            ["applied_copy"] = "📋 Copiar",
            ["applied_copied"] = "✓ Copiado",
            ["applied_copy_tooltip"] = "Copiar este resumen (útil para informes de errores).",
            ["skin_label"] = "Skin",
            ["no_variants"] = "Ningún skin detectado",
            ["not_configured"] = "Sin configuración",
            ["modal_title"] = "Sts2 Skin Manager",
            ["modal_body"] = "Para cambiar el skin, STS2 debe reiniciarse.\nElige: reiniciar ahora o cancelar el cambio.\n\nReinicio automático en {0}s vía Steam.",
            ["load_order_modal_title"] = "Sts2 Skin Manager — Configuración inicial",
            ["load_order_modal_body"] = "Skin Manager debe cargarse antes que otros mods\npara bloquear sus cambios forzados (p. ej. tamaño del personaje).\n\nEl orden de carga de mods se corrigió automáticamente.\nReinicia STS2 una vez para aplicar.\n\nReinicio automático en {0}s vía Steam.",
            ["dll_skin_modal_title"] = "Sts2 Skin Manager — Skin DLL detectado",
            ["dll_skin_modal_body_summary"] = "Se detectaron skins de personaje basados en DLL (mod usa Harmony para sustituirlo).\nAsignación automática a un personaje base — ver registros.\n\nReinicia para gestionarlos como skins normales desde el desplegable.\n\nReinicio automático en {0}s vía Steam.",
            ["btn_restart_now"] = "Reiniciar ahora",
            ["btn_restart_later"] = "Reiniciar después",
            ["card_packs_header"] = "Diseños de cartas",
            ["save_changes"] = "Guardar",
            ["discard_changes"] = "Descartar",
            ["preview_unavailable"] = "sin vista previa",
            ["preview_toggle_tooltip"] = "Alternar vista previa de skin",
            ["mixed_panel_header"] = "Mods mixtos (esqueleto + extras)",
            ["mixed_panel_tooltip"] = "Alternar mods mixtos (esqueleto + extras)",
            ["mixed_vanilla_body_tooltip"] = "Activado: el aspecto sigue tu selección de personaje; se conservan las cartas de este mod. (El mod mixto debe estar activado.)",
            ["vanilla_body_on"] = "Aspecto elegido",
            ["vanilla_body_off"] = "Aspecto del mod",
            ["mixed_indicator_tooltip"] = "📦 Mod mixto — aplica esqueleto + cartas / eventos juntos",
            ["mixed_panel_help"] = "La selección de personaje de arriba se carga primero.",
            ["skin_manager_section_header"] = "Gestor de skins",
        },
        ["ESP"] = new()
        {
            ["applied_copy"] = "📋 Copiar",
            ["applied_copied"] = "✓ Copiado",
            ["applied_copy_tooltip"] = "Copiar este resumen (útil para informes de errores).",
            ["skin_label"] = "Skin",
            ["no_variants"] = "Ningún skin detectado",
            ["not_configured"] = "Sin configuración",
            ["modal_title"] = "Sts2 Skin Manager",
            ["modal_body"] = "Para cambiar el skin, STS2 debe reiniciarse.\nElige: reiniciar ahora o cancelar el cambio.\n\nReinicio automático en {0}s vía Steam.",
            ["load_order_modal_title"] = "Sts2 Skin Manager — Configuración inicial",
            ["load_order_modal_body"] = "Skin Manager debe cargarse antes que otros mods\npara bloquear sus cambios forzados (p. ej. tamaño del personaje).\n\nEl orden de carga de mods se corrigió automáticamente.\nReinicia STS2 una vez para aplicar.\n\nReinicio automático en {0}s vía Steam.",
            ["dll_skin_modal_title"] = "Sts2 Skin Manager — Skin DLL detectado",
            ["dll_skin_modal_body_summary"] = "Se detectaron skins de personaje basados en DLL (mod usa Harmony para sustituirlo).\nAsignación automática a un personaje base — ver registros.\n\nReinicia para gestionarlos como skins normales desde el desplegable.\n\nReinicio automático en {0}s vía Steam.",
            ["btn_restart_now"] = "Reiniciar ahora",
            ["btn_restart_later"] = "Reiniciar después",
            ["card_packs_header"] = "Skins de cartas",
            ["save_changes"] = "Guardar",
            ["discard_changes"] = "Descartar",
            ["preview_unavailable"] = "sin vista previa",
            ["preview_toggle_tooltip"] = "Alternar vista previa de skin",
            ["mixed_panel_header"] = "Mods mixtos (esqueleto + extras)",
            ["mixed_panel_tooltip"] = "Alternar mods mixtos (esqueleto + extras)",
            ["mixed_vanilla_body_tooltip"] = "Activado: el aspecto sigue tu selección de personaje; se conservan las cartas de este mod. (El mod mixto debe estar activado.)",
            ["vanilla_body_on"] = "Aspecto elegido",
            ["vanilla_body_off"] = "Aspecto del mod",
            ["mixed_indicator_tooltip"] = "📦 Mod mixto — aplica esqueleto + cartas / eventos juntos",
            ["mixed_panel_help"] = "La selección de personaje de arriba se carga primero.",
            ["skin_manager_section_header"] = "Gestor de skins",
        },
        ["ITA"] = new()
        {
            ["applied_copy"] = "📋 Copia",
            ["applied_copied"] = "✓ Copiato",
            ["applied_copy_tooltip"] = "Copia questo riepilogo (utile per le segnalazioni di bug).",
            ["skin_label"] = "Skin",
            ["no_variants"] = "Nessuna skin rilevata",
            ["not_configured"] = "Nessuna configurazione",
            ["modal_title"] = "Sts2 Skin Manager",
            ["modal_body"] = "Per cambiare la skin, STS2 deve riavviarsi.\nScegli: riavvia ora o annulla la modifica.\n\nRiavvio automatico tra {0}s tramite Steam.",
            ["load_order_modal_title"] = "Sts2 Skin Manager — Prima configurazione",
            ["load_order_modal_body"] = "Skin Manager deve essere caricato prima degli altri mod\nper bloccare le loro modifiche forzate (es. dimensioni del personaggio).\n\nL'ordine di caricamento dei mod è stato corretto automaticamente.\nRiavvia STS2 una volta per applicare.\n\nRiavvio automatico tra {0}s tramite Steam.",
            ["dll_skin_modal_title"] = "Sts2 Skin Manager — Skin DLL rilevata",
            ["dll_skin_modal_body_summary"] = "Sono state rilevate skin di personaggio basate su DLL (il mod usa Harmony per sostituirla).\nAssegnazione automatica a un personaggio base — vedi i log.\n\nRiavvia per gestirle come normali skin dal menu a discesa.\n\nRiavvio automatico tra {0}s tramite Steam.",
            ["btn_restart_now"] = "Riavvia ora",
            ["btn_restart_later"] = "Riavvia dopo",
            ["card_packs_header"] = "Skin delle carte",
            ["save_changes"] = "Salva",
            ["discard_changes"] = "Annulla",
            ["preview_unavailable"] = "nessuna anteprima",
            ["preview_toggle_tooltip"] = "Attiva/disattiva anteprima skin",
            ["mixed_panel_header"] = "Mod misti (spine + extra)",
            ["mixed_panel_tooltip"] = "Attiva/disattiva mod misti (spine + extra)",
            ["mixed_vanilla_body_tooltip"] = "Attivo: l'aspetto segue la selezione del personaggio; le carte di questo mod restano. (Il mod misto deve essere attivo.)",
            ["vanilla_body_on"] = "Aspetto scelto",
            ["vanilla_body_off"] = "Aspetto del mod",
            ["mixed_indicator_tooltip"] = "📦 Mod misto — applica spine + carte / eventi insieme",
            ["mixed_panel_help"] = "La scelta del personaggio sopra viene caricata per prima.",
            ["skin_manager_section_header"] = "Gestore skin",
        },
        ["PTB"] = new()
        {
            ["applied_copy"] = "📋 Copiar",
            ["applied_copied"] = "✓ Copiado",
            ["applied_copy_tooltip"] = "Copiar este resumo (útil para relatórios de bug).",
            ["skin_label"] = "Skin",
            ["no_variants"] = "Nenhuma skin detectada",
            ["not_configured"] = "Sem configuração",
            ["modal_title"] = "Sts2 Skin Manager",
            ["modal_body"] = "Para mudar a skin, o STS2 precisa reiniciar.\nEscolha: reiniciar agora ou cancelar a mudança.\n\nReinício automático em {0}s via Steam.",
            ["load_order_modal_title"] = "Sts2 Skin Manager — Configuração inicial",
            ["load_order_modal_body"] = "O Skin Manager precisa carregar antes dos outros mods\npara bloquear suas alterações forçadas (ex. tamanho do personagem).\n\nA ordem de carregamento dos mods foi corrigida automaticamente.\nReinicie o STS2 uma vez para aplicar.\n\nReinício automático em {0}s via Steam.",
            ["dll_skin_modal_title"] = "Sts2 Skin Manager — Skin DLL detectada",
            ["dll_skin_modal_body_summary"] = "Foram detectadas skins de personagem baseadas em DLL (mod usa Harmony para substituir).\nAtribuição automática a um personagem base — ver logs.\n\nReinicie para gerenciá-las como skins normais pelo menu suspenso.\n\nReinício automático em {0}s via Steam.",
            ["btn_restart_now"] = "Reiniciar agora",
            ["btn_restart_later"] = "Reiniciar depois",
            ["card_packs_header"] = "Skins de cartas",
            ["save_changes"] = "Salvar",
            ["discard_changes"] = "Descartar",
            ["preview_unavailable"] = "sem pré-visualização",
            ["preview_toggle_tooltip"] = "Alternar pré-visualização da skin",
            ["mixed_panel_header"] = "Mods mistos (spine + extras)",
            ["mixed_panel_tooltip"] = "Alternar mods mistos (spine + extras)",
            ["mixed_vanilla_body_tooltip"] = "Ligado: a aparência segue sua seleção de personagem; as cartas deste mod são mantidas. (O mod misto deve estar ativo.)",
            ["vanilla_body_on"] = "Aparência escolhida",
            ["vanilla_body_off"] = "Aparência do mod",
            ["mixed_indicator_tooltip"] = "📦 Mod misto — aplica spine + arte de cartas / eventos juntos",
            ["mixed_panel_help"] = "A escolha de personagem acima carrega primeiro.",
            ["skin_manager_section_header"] = "Gerenciador de skins",
        },
        ["POR"] = new()
        {
            ["applied_copy"] = "📋 Copiar",
            ["applied_copied"] = "✓ Copiado",
            ["applied_copy_tooltip"] = "Copiar este resumo (útil para relatórios de erro).",
            ["skin_label"] = "Skin",
            ["no_variants"] = "Nenhuma skin detetada",
            ["not_configured"] = "Sem configuração",
            ["modal_title"] = "Sts2 Skin Manager",
            ["modal_body"] = "Para alterar a skin, o STS2 precisa de reiniciar.\nEscolha: reiniciar agora ou cancelar a alteração.\n\nReinício automático em {0}s através do Steam.",
            ["load_order_modal_title"] = "Sts2 Skin Manager — Configuração inicial",
            ["load_order_modal_body"] = "O Skin Manager precisa de carregar antes dos outros mods\npara bloquear as suas alterações forçadas (ex. tamanho da personagem).\n\nA ordem de carregamento dos mods foi corrigida automaticamente.\nReinicie o STS2 uma vez para aplicar.\n\nReinício automático em {0}s através do Steam.",
            ["dll_skin_modal_title"] = "Sts2 Skin Manager — Skin DLL detetada",
            ["dll_skin_modal_body_summary"] = "Foram detetadas skins de personagem baseadas em DLL (mod usa Harmony para substituir).\nAtribuição automática a uma personagem base — ver logs.\n\nReinicie para as gerir como skins normais a partir do menu pendente.\n\nReinício automático em {0}s através do Steam.",
            ["btn_restart_now"] = "Reiniciar agora",
            ["btn_restart_later"] = "Reiniciar mais tarde",
            ["card_packs_header"] = "Skins de cartas",
            ["save_changes"] = "Guardar",
            ["discard_changes"] = "Descartar",
            ["preview_unavailable"] = "sem pré-visualização",
            ["preview_toggle_tooltip"] = "Alternar pré-visualização da skin",
            ["mixed_panel_header"] = "Mods mistos (spine + extras)",
            ["mixed_panel_tooltip"] = "Alternar mods mistos (spine + extras)",
            ["mixed_vanilla_body_tooltip"] = "Ligado: a aparência segue sua seleção de personagem; as cartas deste mod são mantidas. (O mod misto deve estar ativo.)",
            ["vanilla_body_on"] = "Aparência escolhida",
            ["vanilla_body_off"] = "Aparência do mod",
            ["mixed_indicator_tooltip"] = "📦 Mod misto — aplica spine + arte de cartas / eventos juntos",
            ["mixed_panel_help"] = "A escolha de personagem acima é carregada primeiro.",
            ["skin_manager_section_header"] = "Gestor de skins",
        },
        ["POL"] = new()
        {
            ["applied_copy"] = "📋 Kopiuj",
            ["applied_copied"] = "✓ Skopiowano",
            ["applied_copy_tooltip"] = "Skopiuj to podsumowanie (przydatne do zgłaszania błędów).",
            ["skin_label"] = "Skin",
            ["no_variants"] = "Nie wykryto skinów",
            ["not_configured"] = "Brak konfiguracji",
            ["modal_title"] = "Sts2 Skin Manager",
            ["modal_body"] = "Aby zmienić skina, STS2 musi się zrestartować.\nWybierz: zrestartuj teraz lub anuluj zmianę.\n\nAutomatyczny restart za {0}s przez Steam.",
            ["load_order_modal_title"] = "Sts2 Skin Manager — Pierwsza konfiguracja",
            ["load_order_modal_body"] = "Skin Manager musi załadować się przed innymi modami,\naby zablokować ich wymuszone zmiany (np. rozmiar postaci).\n\nKolejność ładowania modów została automatycznie poprawiona.\nUruchom STS2 ponownie, aby zastosować.\n\nAutomatyczny restart za {0}s przez Steam.",
            ["dll_skin_modal_title"] = "Sts2 Skin Manager — Wykryto skin DLL",
            ["dll_skin_modal_body_summary"] = "Wykryto skiny postaci oparte na DLL (mod używa Harmony do podmiany).\nAutomatycznie przypisano do bazowej postaci — szczegóły w logach.\n\nZrestartuj, aby zarządzać nimi jak zwykłymi skinami z listy rozwijanej.\n\nAutomatyczny restart za {0}s przez Steam.",
            ["btn_restart_now"] = "Zrestartuj teraz",
            ["btn_restart_later"] = "Zrestartuj później",
            ["card_packs_header"] = "Skiny kart",
            ["save_changes"] = "Zapisz",
            ["discard_changes"] = "Odrzuć",
            ["preview_unavailable"] = "brak podglądu",
            ["preview_toggle_tooltip"] = "Przełącz podgląd skina",
            ["mixed_panel_header"] = "Mody mieszane (szkielet + dodatki)",
            ["mixed_panel_tooltip"] = "Przełącz mody mieszane (szkielet + dodatki)",
            ["mixed_vanilla_body_tooltip"] = "Wł.: wygląd zależy od wyboru postaci; karty tego moda zostają. (Mieszany mod musi być włączony.)",
            ["vanilla_body_on"] = "Wybrany wygląd",
            ["vanilla_body_off"] = "Wygląd moda",
            ["mixed_indicator_tooltip"] = "📦 Mod mieszany — stosuje szkielet + grafiki kart / wydarzeń razem",
            ["mixed_panel_help"] = "Wybór postaci powyżej ładuje się najpierw.",
            ["skin_manager_section_header"] = "Menedżer skinów",
        },
        ["RUS"] = new()
        {
            ["applied_copy"] = "📋 Копировать",
            ["applied_copied"] = "✓ Скопировано",
            ["applied_copy_tooltip"] = "Скопировать эту сводку (удобно для отчётов об ошибках).",
            ["skin_label"] = "Скин",
            ["no_variants"] = "Скины не обнаружены",
            ["not_configured"] = "Без конфигурации",
            ["modal_title"] = "Sts2 Skin Manager",
            ["modal_body"] = "Чтобы изменить скин, STS2 должен перезапуститься.\nВыберите: перезапустить сейчас или отменить изменение.\n\nАвтоматический перезапуск через {0}с через Steam.",
            ["load_order_modal_title"] = "Sts2 Skin Manager — Первая настройка",
            ["load_order_modal_body"] = "Skin Manager должен загружаться раньше других модов,\nчтобы блокировать их принудительные изменения (например, размер персонажа).\n\nПорядок загрузки модов был автоматически исправлен.\nПерезапустите STS2 один раз, чтобы применить.\n\nАвтоматический перезапуск через {0}с через Steam.",
            ["dll_skin_modal_title"] = "Sts2 Skin Manager — Обнаружен DLL-скин",
            ["dll_skin_modal_body_summary"] = "Обнаружены скины персонажей на основе DLL (мод использует Harmony для подмены).\nАвтоматически привязано к базовому персонажу — подробности в логах.\n\nПерезапустите, чтобы управлять ими как обычными скинами через выпадающее меню.\n\nАвтоматический перезапуск через {0}с через Steam.",
            ["btn_restart_now"] = "Перезапустить сейчас",
            ["btn_restart_later"] = "Перезапустить позже",
            ["card_packs_header"] = "Скины карт",
            ["save_changes"] = "Сохранить",
            ["discard_changes"] = "Отмена",
            ["preview_unavailable"] = "нет превью",
            ["preview_toggle_tooltip"] = "Переключить превью скина",
            ["mixed_panel_header"] = "Смешанные моды (спайн + дополнения)",
            ["mixed_panel_tooltip"] = "Переключить смешанные моды (спайн + дополнения)",
            ["mixed_vanilla_body_tooltip"] = "Вкл.: облик следует за выбором персонажа; карты этого мода сохраняются. (Смешанный мод должен быть включён.)",
            ["vanilla_body_on"] = "Выбранный вид",
            ["vanilla_body_off"] = "Вид мода",
            ["mixed_indicator_tooltip"] = "📦 Смешанный мод — применяет спайн + арт карт / события вместе",
            ["mixed_panel_help"] = "Выбор персонажа сверху загружается первым.",
            ["skin_manager_section_header"] = "Менеджер скинов",
        },
        ["THA"] = new()
        {
            ["applied_copy"] = "📋 คัดลอก",
            ["applied_copied"] = "✓ คัดลอกแล้ว",
            ["applied_copy_tooltip"] = "คัดลอกสรุปนี้ (สะดวกสำหรับการรายงานบั๊ก).",
            ["skin_label"] = "สกิน",
            ["no_variants"] = "ไม่พบสกิน",
            ["not_configured"] = "ไม่มีการตั้งค่า",
            ["modal_title"] = "Sts2 Skin Manager",
            ["modal_body"] = "การเปลี่ยนสกินต้องรีสตาร์ท STS2\nเลือก: รีสตาร์ทตอนนี้ หรือยกเลิกการเปลี่ยนแปลง\n\nรีสตาร์ทอัตโนมัติใน {0} วินาที ผ่าน Steam",
            ["load_order_modal_title"] = "Sts2 Skin Manager — การตั้งค่าครั้งแรก",
            ["load_order_modal_body"] = "Skin Manager ต้องโหลดก่อน mod อื่น\nเพื่อบล็อกการเปลี่ยนแปลงที่ถูกบังคับ (เช่น การกำหนดขนาดตัวละคร)\n\nลำดับการโหลด mod ได้รับการแก้ไขโดยอัตโนมัติ\nกรุณารีสตาร์ท STS2 หนึ่งครั้งเพื่อใช้งาน\n\nรีสตาร์ทอัตโนมัติใน {0} วินาที ผ่าน Steam",
            ["dll_skin_modal_title"] = "Sts2 Skin Manager — ตรวจพบสกิน DLL",
            ["dll_skin_modal_body_summary"] = "ตรวจพบสกินตัวละครที่ใช้ DLL (mod ใช้ Harmony เพื่อสลับ)\nกำหนดให้ตัวละครพื้นฐานโดยอัตโนมัติ — ดูรายละเอียดใน log\n\nรีสตาร์ทเพื่อจัดการเหมือนสกินทั่วไปจากเมนูแบบเลื่อนลง\n\nรีสตาร์ทอัตโนมัติใน {0} วินาที ผ่าน Steam",
            ["btn_restart_now"] = "รีสตาร์ทตอนนี้",
            ["btn_restart_later"] = "รีสตาร์ทภายหลัง",
            ["card_packs_header"] = "สกินการ์ด",
            ["save_changes"] = "บันทึก",
            ["discard_changes"] = "ยกเลิก",
            ["preview_unavailable"] = "ไม่มีตัวอย่าง",
            ["preview_toggle_tooltip"] = "สลับการแสดงตัวอย่างสกิน",
            ["mixed_panel_header"] = "ม็อดผสม (สไปน์ + ส่วนเสริม)",
            ["mixed_panel_tooltip"] = "สลับม็อดผสม (สไปน์ + ส่วนเสริม)",
            ["mixed_vanilla_body_tooltip"] = "เปิด: รูปลักษณ์ตามที่เลือกตัวละครด้านบน คงการ์ดของม็อดนี้ไว้ (ต้องเปิดม็อดผสม)",
            ["vanilla_body_on"] = "รูปลักษณ์ที่เลือก",
            ["vanilla_body_off"] = "รูปลักษณ์ม็อด",
            ["mixed_indicator_tooltip"] = "📦 ม็อดผสม — ใช้สไปน์ + อาร์ตการ์ด / อีเวนต์ร่วมกัน",
            ["mixed_panel_help"] = "ตัวเลือกตัวละครด้านบนถูกโหลดก่อน",
            ["skin_manager_section_header"] = "ตัวจัดการสกิน",
        },
        ["TUR"] = new()
        {
            ["applied_copy"] = "📋 Kopyala",
            ["applied_copied"] = "✓ Kopyalandı",
            ["applied_copy_tooltip"] = "Bu özeti kopyala (hata bildirimleri için kullanışlı).",
            ["skin_label"] = "Skin",
            ["no_variants"] = "Skin algılanmadı",
            ["not_configured"] = "Yapılandırma yok",
            ["modal_title"] = "Sts2 Skin Manager",
            ["modal_body"] = "Skini değiştirmek için STS2'nin yeniden başlatılması gerekir.\nSeçin: şimdi yeniden başlat veya değişikliği iptal et.\n\n{0}s sonra Steam ile otomatik yeniden başlatma.",
            ["load_order_modal_title"] = "Sts2 Skin Manager — İlk kurulum",
            ["load_order_modal_body"] = "Skin Manager, diğer modların zorla yaptığı değişiklikleri (ör. karakter boyutu)\nengellemek için diğer modlardan önce yüklenmelidir.\n\nMod yükleme sırası otomatik olarak düzeltildi.\nUygulamak için STS2'yi bir kez yeniden başlatın.\n\n{0}s sonra Steam ile otomatik yeniden başlatma.",
            ["dll_skin_modal_title"] = "Sts2 Skin Manager — DLL skini algılandı",
            ["dll_skin_modal_body_summary"] = "DLL tabanlı karakter skinleri algılandı (mod Harmony ile karakter değiştiriyor).\nOtomatik olarak bir temel karaktere atandı — ayrıntılar için log.\n\nNormal skinler gibi açılır menüden yönetmek için yeniden başlatın.\n\n{0}s sonra Steam ile otomatik yeniden başlatma.",
            ["btn_restart_now"] = "Şimdi yeniden başlat",
            ["btn_restart_later"] = "Sonra yeniden başlat",
            ["card_packs_header"] = "Kart skinleri",
            ["save_changes"] = "Kaydet",
            ["discard_changes"] = "İptal",
            ["preview_unavailable"] = "önizleme yok",
            ["preview_toggle_tooltip"] = "Skin önizlemesini aç/kapat",
            ["mixed_panel_header"] = "Karışık modlar (spine + ek)",
            ["mixed_panel_tooltip"] = "Karışık modları aç/kapat (spine + ek)",
            ["mixed_vanilla_body_tooltip"] = "Açık: görünüm karakter seçimini izler; bu modun kartları kalır. (Karışık mod açık olmalı.)",
            ["vanilla_body_on"] = "Seçilen görünüm",
            ["vanilla_body_off"] = "Mod görünümü",
            ["mixed_indicator_tooltip"] = "📦 Karışık mod — spine + kart sanatını / olayları birlikte uygular",
            ["mixed_panel_help"] = "Yukarıdaki karakter seçimi önce yüklenir.",
            ["skin_manager_section_header"] = "Skin yöneticisi",
        },
    };
}
